### ISSUE TITLE
some ecoinvent locations not available

### ISSUE THREAD

**Issue by brianlcox** [cmutel/constructive_geometries#1]
Hi Chris,

I like this! However, some ecoinvent (v3.3) locations don't seem to be available. Here's a dictionary that I'm using to look up the name that you are using:

fix_names= {'CSG' : 'CN-CSG',
            'SGCC': 'CN-SGCC',
             
             'RFC' : 'US-RFC',
             'SERC' : 'US-SERC',
             'TRE': 'US-TRE',
             'ASCC': 'US-ASCC',
             'HICC': 'US-HICC',
             'FRCC': 'US-FRCC',
             'SPP' : 'US-SPP',
            'MRO, US only' : 'US-MRO', 
             'NPCC, US only': 'US-NPCC', 
             'WECC, US only': 'US-WECC',
             
             'IAI Area, Africa':'IAI Area 1, Africa',
             'IAI Area, South America':'IAI Area 3, South America', 
             'IAI Area, Asia, without China and GCC':'IAI Area 4&5, without China', 
             'IAI Area, North America, without Quebec':'IAI Area 2, without Quebec',
             'IAI Area, Gulf Cooperation Council':'IAI Area 8, Gulf'
            }

**Comment by cmutel** [comment]
Fixed in `bw2io` 0.6.RC5
